version: '3.7'

services:
  nginx: 
    build: ./nginx 
    container_name: nginx
    ports: 
      - "1339:80" 
    volumes:  
      - static_volume:/home/app/joblink/static 
    depends_on: 
      - web 
    restart: "on-failure" 

  web:
    build: . 
    container_name: django-app
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn microservice_sample_app.wsgi:application --bind 0.0.0.0:${APP_PORT}" 
    volumes:
    - static_volume:/home/app/joblink/static
    env_file: 
      - .env
    image: django-joblink
    expose: 
      - ${APP_PORT}
    restart: "on-failure"
    depends_on: 
      - db


  db:
    image: postgres:11-alpine 
    container_name: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}

    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:
