version: '3.7'

services:
  nginx: 
    build: ./nginx 
    container_name: nginx
    ports: 
      - "1339:80" 
    volumes:  
      - static_volume:/home/app/joblink/static 
    depends_on: 
      - web 
    restart: "on-failure" 

  web:
    build: . 
    image: darkecstacy/joblink:${APP_VERSION}
    container_name: django-app
    command: sh -c "cd JobLink &&
                    pip3 install gunicorn &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn JobLink.wsgi:application --bind 0.0.0.0:${APP_PORT}" 
    volumes:
    - static_volume:/home/app/joblink/static
    env_file: 
      - .env
    expose:
      - ${APP_PORT}
    ports: 
      - 5556:${APP_PORT}
    restart: "on-failure"

volumes:
  static_volume:
